ERP/core/urls.py
from django.urls import path
from ERP.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('produto/<int:pk>/json/', v.produto_json, name='produto_json'),
    ]

ERP/estoque/urls.py
from django.urls import include, path
from ERP.estoque import views as v, lista_view as l


app_name = 'estoque'


entrada_patterns = [
    path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

saida_patterns = [
    path('', v.estoque_saida_list, name='estoque_saida_list'),
    path('sem_pedido/', v.sem_pedido, name='sem_pedido'),
    #path('add/', v.estoque_saida_add, name='estoque_saida_add'),
]

urlpatterns = [
    path('enviar/<int:pk>/', v.pedido_enviar, name='enviar'),
    path('lista/', l.lista_itens, name='lista_ativa'),
    path('lista_print/', l.lista_print, name='lista_print'),
    path('finalizar/', v.finalizar, name='finalizar'),
    path('encerrar/', v.reiniciar, name='encerrar'),
	path('pedido/', v.pedido_edit, name='pedido_update'),
    path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
    path('controle/', v.controle, name='controle'),
]

ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),

    path('', include('ERP.core.urls')),
    path('estoque/', include('ERP.estoque.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

ERP/core/models.py
from django.db import models
from enum import Enum
#from django.contrib.auth.models import AbstractUser
#from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your models here.

class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'Criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'Modificado em',
        auto_now_add=False,
        auto_now=True,
        blank=True, null=True
    )
    class Meta:
        abstract = True

class ChoiceEnum(Enum):
    @classmethod
    def choices(cls):
        return tuple((x.name, x.value) for x in cls)

class Tipo(ChoiceEnum):
    COTISTA = 'Cotista'
    TRABALHADOR = 'Trabalhador'
    BOLSISTA = 'Bolsista'
    APOIADOR = 'Apoiador'
    PERMUTA = 'Permuta'
    VOLUNTARIO = 'Voluntário'


class Status(ChoiceEnum):
    ATIVO = 'Ativo'
    INATIVO = 'Inativo'
    AVISO = 'Aviso Prévio'
    SUSPENSO = 'Suspenso'


class Partilha(models.Model):
    partilha = models.CharField('Partilha', max_length=50, unique=True)
    icone = models.CharField('Ícone', max_length=50, blank=True, null=True)

    def __str__(self):
        return self.partilha


class Fornecedor(models.Model):

    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Item(models.Model):

    produto = models.CharField('Item', max_length=70, unique=True)
    saldo = models.IntegerField('Saldo Atual', default=0)
    preco = models.DecimalField('Preço R$', max_digits=7, decimal_places=2, default=0)
    fornecedor = models.ForeignKey(Fornecedor,
                                   on_delete=models.PROTECT, default=1)

    def get_absolute_url(self):
        return reverse_lazy('core:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto':  self.produto,
            'saldo':  self.saldo,
            'preco':    self.preco,
        }

    class Meta:
        verbose_name_plural = "Itens"
        ordering = ('produto',)

    def __str__(self):
        return self.produto


class CoAgri(models.Model):

    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    dt_nascimento = models.DateField('Data de Nascimento', null=True, blank=True)
    apelido = models.CharField('Apelido', max_length=50, unique=True, null=True, blank=True)
    tipo = models.CharField('Tipo', choices=Tipo.choices(), default=Tipo.COTISTA, max_length=15, null=True, blank=True)
    status = models.CharField('Status', choices=Status.choices(), default=Status.ATIVO, max_length=15)
    higieniza = models.BooleanField('Higieniza', default=True)
    retira = models.BooleanField('Retira', default=False)
    partilha = models.ForeignKey(Partilha,
                                        on_delete=models.PROTECT, null=True, blank=True)

    telefone = models.BigIntegerField('Telefone', null=True, blank=True)
    credito = models.IntegerField('Crédito Semanal', default = 8)
    id_cota = models.IntegerField('Código Cota', null=True, blank=True)

    class Meta:
        ordering = ('user', 'apelido', )

    def __str__(self):
        if self.apelido:
            x = self.apelido
        elif self.user.first_name:
            x = '{} {}'.format(self.user.first_name, self.user.last_name).strip()
        elif self.user.email:
            x = self.user.email
        else:
            x = self.user.username
        return x


class Situacao(models.Model):
    nome = models.CharField(max_length=25)
    valor = models.BooleanField(default=False)

ERP/core/forms.py
from django import forms
from .models import Item, Situacao


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = '__all__'


class SituacaoForm(forms.ModelForm):

    class Meta:
        model = Situacao
        fields = '__all__'

ERP/core/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView
from .models import Item as Produto, Situacao
from .forms import ItemForm as ProdutoForm, SituacaoForm

# Create your views here.

def index(request):
    return render(request, 'index.html')

def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    search = request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list': objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 10


def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def produto_add(request):
    form = ProdutoForm(request.POST or None)
    template_name = 'produto_form2.html'

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('produto:produto_list'))

    context = {'form': form}
    return render(request, template_name, context)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class SituacaoUpdate(UpdateView):
    model = Situacao
    template_name = 'situacao.html'
    form_class = SituacaoForm


def produto_json(request, pk):
    ''' Retorna o produto, id e estoque. '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        produto = item.get('produto')
        estoque = item.get('estoque')
        obj = Produto(
            produto=produto,
            estoque=estoque,
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)

ERP/core/templates/includes/nav.html
<!--https://getbootstrap.com/docs/4.0/components/navbar/ -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Listas & Pedidos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <!--a class="nav-link" href="#">Login</a-->
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_superuser %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Lista
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_add' %}">Criar Lista</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'estoque:controle' %}">Controle</a>
          </li>
      {% endif %}
      {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'estoque:pedido_update' %}">Fazer Pedido</a>
          </li>
      {% endif %}
      {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Relatórios
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'estoque:lista_ativa' %}">Separação Horta</a>
                <a class="dropdown-item" href="{% url 'estoque:lista_print' %}">Resumo por Coagri</a>
                <a class="dropdown-item" href="{% url 'estoque:sem_pedido' %}">Sem Pedido</a>
              {% if user.is_superuser %}
                  <div class="dropdown-divider">Histórico</div>
                        <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Listas</a>
                        <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Pedidos</a>
              {% endif %}
            </div>
          </li>
      {% endif %}
      {% if user.is_superuser %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'admin:auth_user_changelist' %}">Usuários e Coagris</a>
              <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Home</a>
            </div>
          </li>
      {% endif %}

    </ul>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a href="{% url 'password_reset' %}" class="nav-link">Mudar a Senha</a>
        </li>
    {% if user.is_authenticated %}
        <li class="nav-item text-nowrap">
          <a href="{% url 'logout' %}" class="nav-link">Sair</a>
        </li>
      </ul>
    {% endif %}
  </div>
</nav>