ERP/estoque/urls.py
from django.urls import include, path
from ERP.estoque import views as v, lista_view as l


app_name = 'estoque'


entrada_patterns = [
    path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

saida_patterns = [
    path('', v.estoque_saida_list, name='estoque_saida_list'),
    path('sem_pedido/', v.sem_pedido, name='sem_pedido'),
    #path('add/', v.estoque_saida_add, name='estoque_saida_add'),
]

urlpatterns = [
    path('enviar/<int:pk>/', v.pedido_enviar, name='enviar'),
    path('lista/', l.lista_itens, name='lista_ativa'),
    path('lista_print/', l.lista_print, name='lista_print'),
    path('finalizar/', v.finalizar, name='finalizar'),
    path('encerrar/', v.reiniciar, name='encerrar'),
	path('pedido/', v.pedido_edit, name='pedido_update'),
    path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
    path('controle/', v.controle, name='controle'),
]

ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),

    path('', include('ERP.core.urls')),
    path('estoque/', include('ERP.estoque.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

ERP/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from ERP.core.models import TimeStampedModel, Item
from .managers import ListaManager, PedidoManager
import decimal


MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
    ('f', 'fechamento'),
)


class Estoque(TimeStampedModel):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO, blank=True)
    aberto = models.BooleanField(default=True)
    finaliza = models.DateField(verbose_name='Finaliza em', blank=True, null=True)

    class Meta:
        ordering = ('-finaliza', 'usuario',)

    @property
    def total(self):
        total = list(EstoqueItens.objects.filter(estoque=self, produto__preco=decimal.Decimal(0)).aggregate(models.Sum('quantidade')).values())[0]
        return total

    @property
    def preco_total(self):
        x = decimal.Decimal(0)
        for item in EstoqueItens.objects.filter(estoque=self):
            x = x + (decimal.Decimal(item.quantidade) * item.preco)
        return x

    def __str__(self):
        try:
            fim = self.finaliza.strftime('%d-%m-%Y')
        except:
            fim = None
        try:
            coagri = self.usuario
        except:
            coagri = None
        return '{} - {} - {}'.format(coagri, fim, self.pk)


class Lista(Estoque):

    objects = ListaManager()

    class Meta:
        proxy = True
        verbose_name = 'Lista (Entrada)'
        verbose_name_plural = 'Listas (Entradas)'

    def save(self, *args, **kwargs):
        self.movimento = 'e'
        super(Lista, self).save(*args, **kwargs)


class Pedido(Estoque):

    objects = PedidoManager()

    class Meta:
        proxy = True
        verbose_name = 'Pedido (Saída)'
        verbose_name_plural = 'Pedidos (Saídas)'

    def save(self, *args, **kwargs):
        self.movimento = 's'
        super(Pedido, self).save(*args, **kwargs)


class EstoqueItens(models.Model):
    estoque = models.ForeignKey(
        Estoque,
        on_delete=models.CASCADE,
        related_name='estoques'
    )
    produto = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()

    class Meta:
        ordering = ('pk',)
        unique_together = ('estoque', 'produto',)

    def __str__(self):
        return '{} - {} - {}'.format(self.pk, self.estoque.pk, self.produto)

    @property
    def saldo(self):
        return self.produto.saldo

    @property
    def preco(self):
        return self.produto.preco

ERP/estoque/forms.py
from django import forms
from ERP.core.models import Item
from .models import Estoque, EstoqueItens
import logging

logger = logging.getLogger(__name__)


class EstoqueForm(forms.ModelForm):
    class Meta:
        model = Estoque
        fields = ('finaliza', )

    def __init__(self, *args, **kwargs):
        super(EstoqueForm, self).__init__(*args, **kwargs)
        self.fields['finaliza'].required = True


class EstoqueItensForm(forms.ModelForm):
    class Meta:
        model = EstoqueItens
        fields = '__all__'


class PedidoItemForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'

    def clean_quantidade(self):
        for field_name in self.changed_data:
            if field_name == 'quantidade':
                e = self.cleaned_data.get('estoque')
                velho = 0
                if self.cleaned_data.get('produto') is not None:
                    preco = Item.objects.get(produto=self.cleaned_data.get('produto')).preco
                    nome_item = Item.objects.get(produto=self.cleaned_data.get('produto')).produto
                    saldo_item = Item.objects.get(produto=self.cleaned_data.get('produto')).saldo
                else:
                    preco = 0
                    saldo_item = 0
                if EstoqueItens.objects.filter(produto=self.cleaned_data.get('produto'), estoque=e):
                    velho = EstoqueItens.objects.filter(produto=self.cleaned_data.get('produto'), estoque=e).first().quantidade
                novo = self.cleaned_data.get('quantidade')
                if e.total is None:
                    saldo = e.usuario.coagri.credito
                else:
                    saldo = e.usuario.coagri.credito - e.total
                diferenca = novo - velho
                #logger.error(preco)
                if diferenca > saldo and preco < 0.01:
                    raise forms.ValidationError('Quantidade Total Excede o Crédito Semanal')
                if saldo_item - diferenca < 0:
                    raise forms.ValidationError('Excede Saldo de %s', nome_item)
        return self.cleaned_data.get('quantidade')


    def __init__(self, *args, **kwargs):
        super(PedidoItemForm, self).__init__(*args, **kwargs)
        # Retorna somente produtos com estoque maior do que zero.
        itens = Item.objects.filter(saldo__gt=0)
        try:
            item = Item.objects.filter(pk=self.instance.produto.id)
            itens |= item
        except:
            pass
        self.fields['produto'].queryset = itens

ERP/estoque/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max, Sum
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url, redirect
from django.views.generic import ListView, DetailView #, UpdateView
from ERP.core.models import CoAgri, Item #, Situacao
from .models import Estoque, Lista as EstoqueEntrada, Pedido as EstoqueSaida, EstoqueItens
from .forms import EstoqueForm, EstoqueItensForm, PedidoItemForm
from django.db import connection
from django.contrib import messages
from django.contrib.auth.models import User
from ERP.estoque.email import email_abertura, email_fechamento, email_pedido
import logging

logger = logging.getLogger(__name__)


def estoque_entrada_list(request):
    template_name = 'estoque_list.html'
    objects = EstoqueEntrada.objects.all()
    context = {
        'object_list': objects,
        'titulo': 'Lista',
        'url_add': 'estoque:estoque_entrada_add',
    }
    return render(request, template_name, context)


class EstoqueEntradaList(ListView):
    model = EstoqueEntrada
    template_name = 'estoque_list.html'

    def get_context_data(self, **kwargs):
        context = super(EstoqueEntradaList, self).get_context_data(**kwargs)
        context['titulo'] = 'Lista'
        context['url_add'] = 'estoque:estoque_entrada_add'
        return context


def estoque_entrada_detail(request, pk):
    template_name = 'estoque_detail.html'
    obj = EstoqueEntrada.objects.get(pk=pk)
    context = {
        'object': obj,
        'url_list': 'estoque:estoque_entrada_list'
    }
    return render(request, template_name, context)


class EstoqueDetail(DetailView):
    model = Estoque
    template_name = 'estoque_detail.html'


def recalcular_estoque():
    entradas = EstoqueItens.objects.filter(estoque__movimento='e', estoque__aberto=True)
    entradas = entradas.values('produto').annotate(entrada=Sum('quantidade'))
    saidas = EstoqueItens.objects.filter(estoque__movimento='s', estoque__aberto=True)
    saidas = saidas.values('produto').annotate(saida=Sum('quantidade'))
    for produto in entradas:
        item = Item.objects.get(pk=produto['produto'])
        try:
            saida_dict = saidas.get(produto=produto['produto'])
            saida = saida_dict['saida']
        except ObjectDoesNotExist:
            saida = 0

        entrada = produto['entrada']
        item.saldo = entrada - saida
        item.save()


@login_required(login_url='login/')
def finalizar(request):
    cursor1 = connection.cursor()
    cursor1.execute("update estoque_estoque set aberto = FALSE")
    email_fechamento()
    messages.success(request, 'Finalizado com sucesso')
    return redirect('estoque:controle')


@login_required(login_url='login/')
def reiniciar(request):
    cursor1 = connection.cursor()
    cursor1.execute("update core_item as c set c.saldo = 0")
    cursor1.execute("update estoque_estoque set aberto = FALSE")
    messages.success(request, 'Encerrado com sucesso')
    return redirect('estoque:controle')


@login_required(login_url='login/')
def pedido_enviar(request, pk):
    listinha = EstoqueItens.objects.filter(estoque=pk)
    mensagem = 'Pedido:\n\t\t'
    for ei in listinha:
        if ei.quantidade > 0:
            mensagem = mensagem + '%s - %s;\n\t\t' % (ei.produto, ei.quantidade)
    mensagem = mensagem + 'Confirmado.'
    messages.success(request, mensagem)
    email_pedido(request.user, mensagem)
    return redirect('core:index')


def estoque_add(request, template_name, movimento, url):
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(
        Estoque,
        EstoqueItens,
        form=EstoqueItensForm,
        extra=0,
        can_delete=False,
        min_num=1,
        validate_min=True,
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form, prefix='main')
        formset = item_estoque_formset(
            request.POST,
            instance=estoque_form,
            prefix='estoque'
        )
        if form.is_valid() and formset.is_valid():
            form = form.save(commit=False)
            form.usuario = request.user
            form.movimento = movimento
            form.save()
            formset.save()
            recalcular_estoque()
            email_abertura()
            return {'pk': form.pk}
    else:
        form = EstoqueForm(instance=estoque_form, prefix='main')
        formset = item_estoque_formset(instance=estoque_form, prefix='estoque')
    context = {'form': form, 'formset': formset}
    return context


@login_required(login_url='login/')
def estoque_entrada_add(request):
    template_name = 'estoque_entrada_form.html'
    movimento = 'e'
    url = 'estoque:estoque_detail'
    context = estoque_add(request, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url, context.get('pk')))
    return render(request, template_name, context)


def estoque_saida_list(request):
    template_name = 'estoque_list.html'
    objects = Estoque.objects.filter(aberto=True,
                                     movimento='s')
    context = {
        'object_list': objects,
        'titulo': 'Pedido',
        'url_add': 'estoque:pedido_update'
    }
    return render(request, template_name, context)


def estoque_saida_detail(request, pk):
    template_name = 'estoque_detail.html'
    obj = EstoqueSaida.objects.get(pk=pk)
    context = {
        'object': obj,
        'url_list': 'estoque:estoque_saida_list'
    }
    return render(request, template_name, context)


@login_required(login_url='login/')
def pedido_edit(request):
    coagri = CoAgri.objects.get(user=request.user)
    if coagri.status == 'ATIVO' or coagri.status == 'AVISO':
        if request.user.is_superuser == True:
            q = Estoque.objects.filter(movimento='e').aggregate(fim=Max('finaliza'))
        else:    
            q = Estoque.objects.filter(aberto=True, movimento='e').aggregate(fim=Max('finaliza'))
        finaliza = q['fim']
        if finaliza is not None:
            try:
                pedido = Estoque.objects.get(aberto=True, movimento='s', usuario=request.user)
                #pedido = pedido[0]
            except Estoque.DoesNotExist:
                pedido = Estoque(
                            aberto=True,
                            movimento='s',
                            finaliza=finaliza,
                            usuario=request.user
                                )
                pedido.save()
        else:
            messages.warning(request, 'Sem lista aberta. Por favor aguarde.')
            return redirect('core:index')
    else:
        messages.error(request, 'CoAgricultor sem permissão para Pedidos')
        return redirect('core:index')

    pedido_itens_formset = inlineformset_factory(
                                Estoque,
                                EstoqueItens,
                                form=PedidoItemForm,
                                extra=1,
                                can_delete=False)

    itens = pedido_itens_formset(request.POST or None, instance=pedido, prefix='item')
    if request.method == 'POST':
        if itens.is_valid():
            itens.save()
            recalcular_estoque()
            messages.success(request, 'Item atualizado com sucesso')
            return HttpResponseRedirect(resolve_url('estoque:pedido_update'))
        messages.error(request, 'Pedido não Salvo')
        return HttpResponseRedirect(resolve_url('estoque:pedido_update'))

    return render(request, 'pedido_update.html',
        {"itens": itens, "pedido": pedido, "coagri": coagri})

@login_required(login_url='login/')
def controle(request):
    template_name = 'controle.html'
    return render(request, template_name, {"titulo":'Controle de Fechamento'})


def sem_pedido(request):
    template_name = 'sem_pedido.html'
    objects = User.objects.exclude(
        coagri__status='INATIVO',
        )
    objects = objects.exclude(
        coagri__status='SUSPENSO',
        )
    objects = objects.exclude(
        coagri__credito=0,
        )
    objects = objects.exclude(
        estoque__aberto=True,
        estoque__movimento='s',
        ).order_by('coagri__partilha', 'coagri__higieniza', 'first_name', 'last_name', 'username')
    context = {
        'object_list': objects,
        'titulo': 'Sem Pedido',
    }
    return render(request, template_name, context)

ERP/estoque/templates/controle.html
{% extends "base.html" %}

{% block title %}
<h2>{{ titulo }}</h2>
{% endblock title %}

{% block content %}
    {% csrf_token %}
    {% if user.is_superuser %}
        <div="container">
            <a  target="_blank"
                class="btn btn-primary pull-left"
                href="{% url 'estoque:finalizar' %}">
                Finalizar Período de Pedidos
            </a></br></br>
            <a  target="_blank"
                class="btn btn-danger pull-right"
                href="{% url 'estoque:encerrar' %}">
                Encerrar Partilha Atual
            </a>
        </div>
    {% endif %}
{% endblock content %}

ERP/estoque/templates/email_lista_criada.html
<html>
<body>
	<h3>Prezad@s,</h3>
	<h3>Os {{ lista_itens.count }} itens desta semana já estão disponíveis para Pedido até dia {{ finaliza }}.</h3>
	</br>
	<h4>Acesse <a href="http://www.CSAAtibaia.in">CSAAtibaia</a> para fazer seu pedido.</h4>
    </br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Saldo</th>
                <th>Item</th>
            </tr>
        </thead>
        <tbody>
            {% for item in lista_itens %}
                <tr>
                    <td><b>{{ item.saldo }}</b></td>
                    <td>{{ item.produto|title }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

	</br>
	<p>Att,</p>
	<p>Horta CSA</p>

    <img src="https://i.imgur.com/G5XJbQD.jpg" alt="Lista Disponível" height="128" width="128">

</body>

<!--    body = 'Prezad@s, Os itens desta semana já estão disponíveis para Pedido até dia %s.\nAcesse http://www.CSAAtibaia.in para fazer seu pedido.\n\nLista: \n' % (finaliza)
    body = body + '%-*s%s\n' % (25, 'Nome', 'Saldo')
    for item in lista_itens:
        for val in item:
            if str(val) == "0.00":
                val=str("")

            a = '%-*s' % (25, str(val))
            body = body + a

        body = body + '\n'

    body = body + '\nAtt, \nHorta CSA'
    -->

ERP/estoque/templates/estoque_detail.html
{% extends "base.html" %}

{% block content %}

{% if object.movimento == 'e' %}
  <a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>
{% else %}
  <a href="{% url 'estoque:estoque_saida_list' %}">Voltar</a>
{% endif %}

{% if object.movimento == 'e' %}
  <h1>Lista: {{ object }}</h1>
{% else %}
  <h1>Pedido: {{ object }}</h1>
{% endif %}

<table class="table table-striped">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Saldo</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object.estoques.all %}
      <tr>
        <td>{{ obj.produto }}</td>
        <td>{{ obj.quantidade }}</td>
        <td>{{ obj.saldo }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

ERP/estoque/templates/estoque_entrada_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
  </style>

{% endblock css %}

{% block content %}

<a href="{% url 'estoque:estoque_entrada_list' %}">Voltar</a>

<div class="row">
  <div class="cols">
    <form method="POST" novalidate>
      {% csrf_token %}
      <legend style="border-bottom: 1px solid #e5e5e5;">Criar Lista</legend>

      <div class="row">
        <div class="col-sm-6">
          {% for field in form.visible_fields %}
            <div class="form-group{% if field.errors %} has-error {% endif%}">
              <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                  <span class="required">{{ field.label }} </span>
                {% else %}
                  {{ field.label }}
                {% endif %}
              </label>
              {% render_field field class="form-control" %}
              {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
              {% endfor %}
            </div>
          {% endfor %}
        {{ formset.management_form }}
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
          <div id="estoque" class="form-inline">
            {% for item_estoque_form in formset %}
              <div id="item-{{ forloop.counter0 }}" class="form-group">
                {{ item_estoque_form|bootstrap }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

      <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
        <i class="fa fa-plus"></i> Adicionar
      </span>

      <div class="row float-right">
        <div class="col-sm-12" style="margin-top: 10px;">
          <div class="form-inline buttons">
            <button class="btn btn-primary" value="Save">
              <i class="fa fa-floppy-o"></i>
              Salvar
            </button>
            <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">
              <i class="fa fa-times"></i>
              Cancelar
            </a>
          </div>
        </div>
      </div>

    </form>
  </div>
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/estoque_entrada.js' %}"></script>

<script type="text/html" id="item-estoque">
  <div id="item-__prefix__" class="form-group">
    {{ formset.empty_form|bootstrap }}
  </div>
</script>


{% endblock js %}

ERP/estoque/templates/estoque_list.html
{% extends "base.html" %}

{% block content %}

<h2>Estoque {{ titulo }}
  {% if user.is_superuser %}
    <span class="pull-right">
      <a href="{% url url_add %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  {% endif %}
</h2>

{{object_list.as_table}}

{% if object_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Id</th>
        <th>Data</th>
        <th>Criador</th>
        <th>Aberta</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{% url 'estoque:estoque_detail' object.pk %}">{{ object.pk }}</a>
          </td>
          <td>{{ object.modified }}</td>
          <td>{{ object.usuario }}</td>
          <td>{{ object.aberto }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

{% endblock content %}

ERP/estoque/templates/estoquesaida_list.html
{% extends "base.html" %}

{% block content %}

<h2>{{ titulo }}</h2>

{% if object_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Id</th>
        <th>Data</th>
        <th>Criador</th>
        <th>Aberta</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list|dictsortreversed:"modified" %}
        <tr>
          <td>
            <a href="{% url 'estoque:estoque_detail' object.pk %}">{{ object.pk }}</a>
          </td>
          <td>{{ object.modified }}</td>
          <td>{{ object.usuario }}</td>
          <td>{{ object.aberto }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

{% endblock content %}

ERP/estoque/templates/itens_coagris_print.html
{% extends "base.html" %}

{% block content %}

<div class="page header">
    <div id="coagris"> <h2>Itens por Coagri</h2>
        {% regroup coagris_tb by entrega_ico as ico_tb %}
            {% for ico in ico_tb %}
            <hr>
                <h4>
                    <i class="{{ ico.grouper }}">
                {% regroup ico.list by entrega as entrega_tb %}
                    {% for entrega in entrega_tb %}
                        {{ entrega.grouper|title }}</i>
                        {% regroup entrega.list by higieniza as higieniza_tb %}
                        {% for higieniza in higieniza_tb %}
                            <!--<h4>{{ higieniza.grouper }}</h4>
                            {% if higieniza.grouper %}
                                <i class="fas fa-shower water"> Pré-Lavados</i>
                            {% else %}
                                <i class="fas fa-tint-slash ok">In Natura</i>
                            {% endif %}-->
                            </h4>
                                <div class="container">
                                    {% regroup higieniza.list by coagri as item_tb %}
                                    {% for coagri in item_tb %}
                                        <b>{{ coagri.grouper|title }}</b>
                                        <div class="container">
                                            <p>
                                            {% for item in coagri.list %}
                                                <b>{{ item.total }}</b> {{ item.nomeitem|title }} ;
                                            {% endfor %}
                                            </p>
                                        </div>
                                    {% endfor %}
                                </div>
                        {% endfor %}
                    {% endfor %}
        {% endfor %}
    </div>

</div>

{% endblock content %}

ERP/estoque/templates/pedido_list.html
{% extends "base.html" %}

{% block content %}

<h2>{{ titulo }}</h2>

{% if object_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Id</th>
        <th>Data</th>
        <th>Criador</th>
        <th>Aberta</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list|dictsortreversed:"modified" %}
        <tr>
          <td>
            <a href="{% url 'estoque:estoque_detail' object.pk %}">{{ object.pk }}</a>
          </td>
          <td>{{ object.modified }}</td>
          <td>{{ object.usuario }}</td>
          <td>{{ object.aberto }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

{% endblock content %}

ERP/estoque/templates/pedido_update.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block content %}

<div class="row">
  <div class="cols">
    <a style="border-bottom: 1px solid #e5e5e5;" href="{% url 'estoque:estoque_saida_list' %}">Histórico</a>
    <form method="POST" novalidate>
      {% csrf_token %}
        <label style="border-bottom: 1px solid #e5e5e5;">Pedido: {{ pedido.usuario|capfirst }} para {{ pedido.finaliza }}</label>
        <b><label>Horta:
        {% if pedido.total == None %}
          0
        {% else %}
          {{ pedido.total }}
        {% endif %}
         de {{ coagri.credito }} | Fornecedores: R${{ pedido.preco_total }}</label></b>
        {% for erro in itens.errors %}
            {% if erro %}
                <div class="alert alert-danger" role="alert">
                    {{ erro }}
                </div>
            {% endif %}
        {% endfor %}
        {{ itens.management_form }}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th style="visibility:collapse;">Id</th>
                    <th>Produto</th>
                    <th>Quantidade</th>
                    <th>Saldo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in itens %}
                    <tr>
                        <td style="visibility:collapse;">{{ item.id }}</td>
                        <td>{% render_field item.produto class="clProduto" %}</td>
                        <td>{% render_field item.quantidade onChange="form.submit();" %}</td>
                        <td>{{ item.instance.saldo }}</td>
                        <td>
                        {% if item.instance.preco > 0 %}
                            R${{ item.instance.preco }}
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="row float-right">
            {% if pedido.total == coagri.credito %}
                <a  class="btn btn-primary pull-right"
                    href="{% url 'estoque:enviar' pedido.id %}">
                    <i class="fa fa-paper-plane" aria-hidden="true"></i>
                    Enviar
                </a>
            {% else %}
                <button type="button" class="btn btn-primary pull-right" disabled>Enviar</button>
            {% endif %}
        </div>
    </form>
  </div>
</div>

{% endblock content %}
{% block js %}
<script src="{% static 'js/pedido.js' %}"></script>
{% endblock js %}

ERP/estoque/templates/sem_pedido.html
{% extends "base.html" %}

{% block content %}

<h2>{{ titulo }}</h2>

{% if object_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Partilha</th>
        <th>Qtde</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list%}
        <tr>
          <td>{{ object.first_name }}</td>
          <td>{{ object.last_name }}</td>
          <td>{{ object.coagri.partilha }}</td>
          <td>{{ object.coagri.credito }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <h4><b>Total:{{ object_list.count }}</b></h4>
{% else %}
  <p class="alert alert-success">Todos pediram!</p>
{% endif %}

{% endblock content %}